title:              "꿀튜브"
tagline:            "유튜브 꿀팁 블로그"
email:              "your-email@example.com"
description:        "유튜브 성장 꿀팁들을 나누는 꿀튜브 블로그입니다."
author:             "홍승채"
baseurl:            "/"
url:                "https://도메인"
locale:             "ko_KR"
thumbnail:          "/img/honeytubethum.png"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
